name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create .env file
      run: |
        touch .env
        echo DUMMY_PASSWORD=${{ secrets.DUMMY_PASSWORD }} >> .env
        echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
        echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
        echo SESSION_SECRET=${{ secrets.SESSION_SECRET }} >> .env

    - run: npm ci
    - run: npm run build --if-present
    - run: npm run coverage
      env:
        CI: true

    - name: Collect coverage to Codecov
      uses: codecov/codecov-action@v1.1.0
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
